#!/bin/bash
## ace-open opens an ace stream with vlc
## Usage: ace-open URL
## Options:
##   -h, --help    Display this message.
##

usage() {
  [ "$*" ] && echo "$0: $*"
  sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
  exit 2
} 2>/dev/null

main() {
  while [ $# -gt 0 ]; do
    case $1 in
    (-h|--help) usage 2>&1;;
    (--) shift; break;;
    (-*) usage "$1: unknown option";;
    (*) break;;
    esac
  done
  if [ $# -ne 1 ]; then
    usage
  fi
  VLC=$(which vlc)
  URL=${1}
  acestream-launcher -p $VLC $URL
}

main "$@"
