#!/bin/bash

set -eu

REPO=$(git remote get-url origin)
BRANCH=$(git branch --show-current)
DIR=$(git rev-parse --show-prefix)
WS=$(terraform workspace show)
VERSION=$(terraform version -json | jq -r '.terraform_version')

echo "- git repository      :"'`'"$REPO"'`'
echo "- git branch          :"'`'"$BRANCH"'`'
echo "- terraformf dir      :"'`'"$DIR"'`'
echo "- terraformf version  :"'`'"$VERSION"'`'
[ "$WS" != "default" ] && echo "- tf workspace :"'`'"$WS"'`'
