#!/bin/sh
aws --region us-west-2 ec2 describe-instances --instance-ids "$@" |
  jq '.Reservations[0].Instances[0]' |
  jq -r '.LaunchTime, .Placement.AvailabilityZone, .InstanceType, .ImageId, .State.Name, .StateReason, .NetworkInterfaces[0].PrivateIpAddresses[0].Association.PublicDnsName'
