#!/bin/sh
## clipath resolves the path of the file given as argument and copies it to the
## system clipboard. The copied paath will be an absolute path, where symlinks
## are resolved and variables like $HOME or ~ are expanded
## Usage: clipath [FILE]
## Options:
##   -h, --help    Display this message.
##

usage() {
  [ "$*" ] && echo "$0: $*"
  sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
  exit 2
} 2>/dev/null

main() {
  while [ $# -gt 0 ]; do
    case $1 in
    (-h|--help) usage 2>&1;;
    (--) shift; break;;
    (-*) usage "$1: unknown option";;
    (*) break;;
    esac
  done
  FILE="${1:-.}"
  readlink -e "${FILE}" | tr -d '\r\n' | xclip -sel cli
}

main "$@"
