#! /bin/bash
## Sorts the biggest files in the current directory by size (recursively).
## Usage: dirsort [N]
##  N: if given, show only the N biggest files. Otherwise show all.
## Options:
##   -h, --help    Display this message.
##

usage() {
  [ "$*" ] && echo "$0: $*"
  sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
  exit 2
} 2>/dev/null

main() {
  while [ $# -gt 0 ]; do
    case $1 in
    (-h|--help) usage 2>&1;;
    (--) shift; break;;
    (-*) usage "$1: unknown option";;
    (*) break;;
    esac
  done

  if [ $# -eq 1 ]; then
    du -a . | sort -h | tail -n "$1"
  else
    du -a . | sort -h
  fi
}

main "$@"
