#! /bin/bash
# create a 'tags' file with gotags, including all files in and under
# the current directory
DST="./tags"
if gotags -f "$DST" -R .
then
  echo go tags generated in ${DST}
else
    echo "error : ${DST} not generated"
fi

#if [ $? -eq 0 ]; then echo go tags generated in \""${DIR}"\"; else echo "an error occured, tags NOT generated"; fi
#popd > /dev/null
