#! /bin/bash
## goversion manages installed go versions
## Examples:
##  - goversion list
##  - goversion download go1.17
##  - goversion select go1.17
##  - goversion show
##
## Options:
##   -h, --help      Display this message.
##   list            List installed go versions.
##   select          selects a go version among the installed ones.
##   download        downloads a new go version.
##

set -eu

usage() {
    [ "$*" ] && echo -e "$(basename $0): $*\n"
    sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
    exit 2
} 2>/dev/null

safewhich() {
    command -v "$1" >/dev/null 2>&1
}

list() {
    find "$gobindir" -type f -executable -regextype posix-extended -regex "${goregex}" |
    sort |
        while read -r line; do basename "$line"; done
}

show() {
    basename $(readlink -e "$gobindir/go")
}

download() {
    version="$1"
    go install "golang.org/dl/$version@latest"
    "$version" download
}

vselect() {
    version="$1"
    [ -x "$gobindir/$version" ] || die "$gobindir/$version not found."
    [ -L "$gobindir/go" ] || die "refusing to overwrite $gobindir/go it's not a symbolic link."
    pushd "$gobindir" >/dev/null || die "pushd $gobindir failed"
    ln -fs "$version" go
    popd >/dev/null || die "popd failed"
    echo "success $(command -v go) is now $(go version)"
}

die() {
    echo "$@"
    exit 1
}

main() {
    while [ $# -gt 0 ]; do
        case $1 in
        show) shift; show ; exit 0;;
        list) shift; list ; exit 0;;
        download)
            shift
            [ $# -ge 1 ] || die "'$(basename $0) download' needs an argument."
            download "$1" ; exit 0
            exit 0
            ;;
        select)
            shift
            [ $# -ge 1 ] || die "'$(basename $0) select' needs an argument."
            vselect "$1" ; exit 0
            ;;
        -h | --help) usage 2>&1 ;;
        *) usage "$1: unknown action" ;;
        esac
    done
    usage
}

safewhich go || die "go binary not found"
gobindir="$(go env GOPATH)/bin"
readonly gobindir
goregex=".*/go((tip)|(1.[0-9]+.*))$"
readonly goregex

main "$@"
