#!/usr/bin/env bash
shopt -s nullglob

declare -a files
declare -A seen
recurse=

append() {
  local f=$1
  [[ -z ${seen[$f]} ]] && files+=("$f") && seen[$f]=1
}

for arg; do
  if [[ $arg == -r ]]; then
    recurse=1
    continue
  fi

  if [[ $recurse ]]; then
    while IFS= read -r -d '' f; do append "$f"; done < <(find "$arg" -type f -print0)
    recurse=
  elif [[ -d $arg ]]; then
    for f in "$arg"/*; do [[ -f $f ]] && append "$f"; done
  else
    for f in $arg; do [[ -f $f ]] && append "$f"; done
  fi
done

for f in "${files[@]}"; do
  printf "## %s\n" "$(realpath --relative-to=. "$f")"
  cat "$f"
done

