#! /bin/bash
## reset-mouse resets the psmouse kernel modules
## this is a temporary workaround to fix the two-fingers scroll stopping to work
## after a suspend, generally this happens on thinkpad.
## Usage: reset-mouse
## Options:
##   -h, --help    Display this message.
##

usage() {
  [ "$*" ] && echo "$0: $*"
  sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
  exit 2
} 2>/dev/null

die () {
  echo "$@"
  exit 1
}

main() {
  while [ $# -gt 0 ]; do
    case $1 in
    (-h|--help) usage 2>&1;;
    (--) shift; break;;
    (-*) usage "$1: unknown option";;
    (*) break;;
    esac
  done

  sudo -v || die "nothing done"
  sudo modprobe -r psmouse
  echo psmouse kernel modules have been removed
  sudo modprobe psmouse
  echo psmouse kernel modules have been added
}

main "$@"
