#!/bin/bash
## Generates a sequence of --target=resource commands to use with terraform,
## when you only want to target a subset of resources which names match a
## a regular expression.
##
## Usage: tftarget EXPR
## Options:
##   -h, --help    Display this message.
##

usage() {
  [ "$*" ] && echo "$0: $*"
  sed -n '/^##/,/^$/s/^## \{0,1\}//p' "$0"
  exit 2
} 2>/dev/null

main() {
  while [ $# -gt 0 ]; do
    case $1 in
    -h | --help) usage 2>&1 ;;
    --)
      shift
      break
      ;;
    -*) usage "$1: unknown option" ;;
    *) break ;;
    esac
  done
  if [ "$1" == "" ]; then
    usage
  fi
  for t in $(terraform state list | grep -E "${1}"); do
    printf "%starget='%s'  \\ \n" "--" "${t}"
  done
}

main "$@"
